<!doctype html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>Yii app generated by Yeoman</title>
</head>
<body>
    <?php echo $content; ?>
</body>
</html>
